"""empty message

Revision ID: 7170c420554d
Revises: 003
Create Date: 2025-11-21 15:16:50.729767

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('data_set_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_set', ['previous_version_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('data_set_ibfk_3'), 'data_set', ['previous_version_id'], ['id'])

    # ### end Alembic commands ###
