"""empty message

Revision ID: 3a9af57f7c6b
Revises: 001
Create Date: 2025-11-15 13:28:03.019526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a9af57f7c6b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: drop the foreign key/column referencing `feature_model` first (see file table alterations below),
    # then drop the `feature_model` table to avoid FK constraint failures.
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), server_default='csv', nullable=False))
        batch_op.create_index(batch_op.f('ix_data_set_type'), ['type'], unique=False)

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_files', sa.String(length=120), nullable=True))
        batch_op.drop_column('number_of_features')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_model_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('file_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_model', ['file_model_id'], ['id'])
        batch_op.drop_column('feature_model_id')

    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=120), nullable=False))
        batch_op.drop_column('uvl_filename')

    # After altering tables that referenced `feature_model` (e.g. dropping the FK/column on `file`),
    # it is now safe to drop the `feature_model` table.
    try:
        op.drop_table('feature_model')
    except Exception:
        # If the table doesn't exist or drop fails for another reason, let the migration continue
        # so the rest of the schema changes still apply. Alembic/DB admins can adjust manually if needed.
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('filename')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('file_model_id')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_features', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('number_of_files')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_set_type'))
        batch_op.drop_column('type')

    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
