"""Add orcid_id and make user fields nullable

Revision ID: d47beaa8d643
Revises: 001
Create Date: 2025-11-10 00:38:13.343620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd47beaa8d643'
down_revision = 'bf0f00a40518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_orcid_id'))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('orcid_id')

    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
