name: Deploy on Render

on:
  workflow_run:
    # Trigger this workflow only after "Pytest" completes
    workflows:
      - "Pytest"
    types:
      - completed

  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Decide deployment target
        id: branch_check
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "Deploying release from main"
            echo "DEPLOY=main" >> $GITHUB_ENV
          elif [ "${{ github.event.workflow_run.conclusion }}" = "success" ] && [ "${{ github.event.workflow_run.head_branch }}" = "trunk" ]; then
            echo "Deploying from trunk (development)"
            echo "DEPLOY=trunk" >> $GITHUB_ENV
          else
            echo "No deploy triggered"
            echo "DEPLOY=none" >> $GITHUB_ENV

      - name: Deploy to Render
        if: env.DEPLOY != 'none'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying branch: $DEPLOY"
          curl "$deploy_url"